// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace NordicArenaTournament.Areas.Admin.Controllers
{
    public partial class TestingController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public TestingController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected TestingController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ScoreAll()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ScoreAll);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public TestingController Actions { get { return MVC.Admin.Testing; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Testing";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Testing";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string ScoreAll = "ScoreAll";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string ScoreAll = "ScoreAll";
        }


        static readonly ActionParamsClass_ScoreAll s_params_ScoreAll = new ActionParamsClass_ScoreAll();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ScoreAll ScoreAllParams { get { return s_params_ScoreAll; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ScoreAll
        {
            public readonly string tournamentId = "tournamentId";
            public readonly string roundNo = "roundNo";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_TestingController : NordicArenaTournament.Areas.Admin.Controllers.TestingController
    {
        public T4MVC_TestingController() : base(Dummy.Instance) { }

        [NonAction]
        partial void ScoreAllOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long tournamentId, int roundNo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ScoreAll(long tournamentId, int roundNo)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ScoreAll);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tournamentId", tournamentId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "roundNo", roundNo);
            ScoreAllOverride(callInfo, tournamentId, roundNo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
