//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NordicArenaDomainModels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NordicArenaDomainModels.Resources.PropertyNames", typeof(PropertyNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alder.
        /// </summary>
        public static string Contestant_AgeYears {
            get {
                return ResourceManager.GetString("Contestant_AgeYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fødselsdato.
        /// </summary>
        public static string Contestant_DateOfBirth {
            get {
                return ResourceManager.GetString("Contestant_DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosted.
        /// </summary>
        public static string Contestant_Location {
            get {
                return ResourceManager.GetString("Contestant_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn.
        /// </summary>
        public static string Contestant_Name {
            get {
                return ResourceManager.GetString("Contestant_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsorer.
        /// </summary>
        public static string Contestant_Sponsors {
            get {
                return ResourceManager.GetString("Contestant_Sponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn.
        /// </summary>
        public static string EditTournamentViewModel_Name {
            get {
                return ResourceManager.GetString("EditTournamentViewModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innloggingskode.
        /// </summary>
        public static string Judge_LoginCode {
            get {
                return ResourceManager.GetString("Judge_LoginCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn.
        /// </summary>
        public static string Judge_Name {
            get {
                return ResourceManager.GetString("Judge_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maks.
        /// </summary>
        public static string JudgingCriterion_Max {
            get {
                return ResourceManager.GetString("JudgingCriterion_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string JudgingCriterion_Min {
            get {
                return ResourceManager.GetString("JudgingCriterion_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervall.
        /// </summary>
        public static string JudgingCriterion_Step {
            get {
                return ResourceManager.GetString("JudgingCriterion_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall deltakere i hvert heat.
        /// </summary>
        public static string Round_ContestantsPerHeat {
            get {
                return ResourceManager.GetString("Round_ContestantsPerHeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maks antall deltakere.
        /// </summary>
        public static string Round_MaxContestants {
            get {
                return ResourceManager.GetString("Round_MaxContestants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall runs per deltaker per runde.
        /// </summary>
        public static string Round_RunsPerContestant {
            get {
                return ResourceManager.GetString("Round_RunsPerContestant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lengde per run i sekunder.
        /// </summary>
        public static string Round_SecondsPerRun {
            get {
                return ResourceManager.GetString("Round_SecondsPerRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tittel.
        /// </summary>
        public static string Round_Title {
            get {
                return ResourceManager.GetString("Round_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karakter.
        /// </summary>
        public static string RoundContestant_TotalScore {
            get {
                return ResourceManager.GetString("RoundContestant_TotalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn.
        /// </summary>
        public static string Tournament_Name {
            get {
                return ResourceManager.GetString("Tournament_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Tournament_Status {
            get {
                return ResourceManager.GetString("Tournament_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avsluttet.
        /// </summary>
        public static string TournamentStatus_Ended {
            get {
                return ResourceManager.GetString("TournamentStatus_Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke startet.
        /// </summary>
        public static string TournamentStatus_Prestart {
            get {
                return ResourceManager.GetString("TournamentStatus_Prestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pågår.
        /// </summary>
        public static string TournamentStatus_Running {
            get {
                return ResourceManager.GetString("TournamentStatus_Running", resourceCulture);
            }
        }
    }
}
