//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NordicArenaDomainModels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NordicArenaDomainModels.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legg til utøver.
        /// </summary>
        public static string AddContestant {
            get {
                return ResourceManager.GetString("AddContestant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legg til runde.
        /// </summary>
        public static string AddNewRound {
            get {
                return ResourceManager.GetString("AddNewRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utøverliste.
        /// </summary>
        public static string AdminContestantListLink {
            get {
                return ResourceManager.GetString("AdminContestantListLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dommerliste.
        /// </summary>
        public static string AdminJudgeListLink {
            get {
                return ResourceManager.GetString("AdminJudgeListLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrasjonsmeny.
        /// </summary>
        public static string AdminMainPageTitle {
            get {
                return ResourceManager.GetString("AdminMainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NordicArena Tournament Administrator.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snitt.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADVARSEL! Dette vil slette alle karakterer, resultater og heatinndeling fra denne runden. Vil du dette?.
        /// </summary>
        public static string ConfirmResetRound {
            get {
                return ResourceManager.GetString("ConfirmResetRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utøver.
        /// </summary>
        public static string Contestant {
            get {
                return ResourceManager.GetString("Contestant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utøverliste.
        /// </summary>
        public static string ContestantList {
            get {
                return ResourceManager.GetString("ContestantList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrer utøverliste.
        /// </summary>
        public static string ContestantListPageTitle {
            get {
                return ResourceManager.GetString("ContestantListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har ikke gitt karakter til deltaker &quot;{0}&quot;. Vil du likevel avslutte karaktergivning?.
        /// </summary>
        public static string ContestantNoScoreWarning {
            get {
                return ResourceManager.GetString("ContestantNoScoreWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utøvere.
        /// </summary>
        public static string Contestants {
            get {
                return ResourceManager.GetString("Contestants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flere deltakere har fortsatt ikke kjørt og/eller blitt karaktersatt.
        /// </summary>
        public static string ContestantsNotScored {
            get {
                return ResourceManager.GetString("ContestantsNotScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utøver {0} har ennå ikke kjørt og/eller blitt karatersatt..
        /// </summary>
        public static string ContestantXNotScored {
            get {
                return ResourceManager.GetString("ContestantXNotScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opprett.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opprett ny.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opprett ny turnering.
        /// </summary>
        public static string CreateTournamentPageTitle {
            get {
                return ResourceManager.GetString("CreateTournamentPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kjører nå.
        /// </summary>
        public static string CurrentContestant {
            get {
                return ResourceManager.GetString("CurrentContestant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slett.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaljer.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rediger.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turneringsoppsett.
        /// </summary>
        public static string EditTournamentPageTitle {
            get {
                return ResourceManager.GetString("EditTournamentPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avslutt.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avslutt
        ///.
        /// </summary>
        public static string EndRound {
            get {
                return ResourceManager.GetString("EndRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finale.
        /// </summary>
        public static string Finals {
            get {
                return ResourceManager.GetString("Finals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overordnet.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat.
        /// </summary>
        public static string Heat {
            get {
                return ResourceManager.GetString("Heat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dommer.
        /// </summary>
        public static string Judge {
            get {
                return ResourceManager.GetString("Judge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dommerliste.
        /// </summary>
        public static string JudgeList {
            get {
                return ResourceManager.GetString("JudgeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrer dommerliste.
        /// </summary>
        public static string JudgeListPageTitle {
            get {
                return ResourceManager.GetString("JudgeListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karakterer.
        /// </summary>
        public static string JudgementListPageTitle {
            get {
                return ResourceManager.GetString("JudgementListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dømming.
        /// </summary>
        public static string JudgePageTitle {
            get {
                return ResourceManager.GetString("JudgePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dommere.
        /// </summary>
        public static string Judges {
            get {
                return ResourceManager.GetString("Judges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dommerstatus.
        /// </summary>
        public static string JudgeStatus {
            get {
                return ResourceManager.GetString("JudgeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferdig.
        /// </summary>
        public static string JudgeSubmitButtonText {
            get {
                return ResourceManager.GetString("JudgeSubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dommerkriterier.
        /// </summary>
        public static string JudgingCriterions {
            get {
                return ResourceManager.GetString("JudgingCriterions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logget inn som.
        /// </summary>
        public static string LoggedInAs {
            get {
                return ResourceManager.GetString("LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny utøver.
        /// </summary>
        public static string NewContestant {
            get {
                return ResourceManager.GetString("NewContestant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny dommer.
        /// </summary>
        public static string NewJudge {
            get {
                return ResourceManager.GetString("NewJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neste utøvere.
        /// </summary>
        public static string NextContestants {
            get {
                return ResourceManager.GetString("NextContestants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ingen deltaker kjører)
        ///.
        /// </summary>
        public static string NoContestant {
            get {
                return ResourceManager.GetString("NoContestant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjern fra turnering.
        /// </summary>
        public static string RemoveContestant {
            get {
                return ResourceManager.GetString("RemoveContestant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultater.
        /// </summary>
        public static string ResultsPageTitle {
            get {
                return ResourceManager.GetString("ResultsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runde.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runden er allerede avsluttet.
        /// </summary>
        public static string RoundAlreadyEnded {
            get {
                return ResourceManager.GetString("RoundAlreadyEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runden er ikke startet.
        /// </summary>
        public static string RoundNotStarted {
            get {
                return ResourceManager.GetString("RoundNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runder.
        /// </summary>
        public static string Rounds {
            get {
                return ResourceManager.GetString("Rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagre.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker.
        /// </summary>
        public static string SpeakerPageTitle {
            get {
                return ResourceManager.GetString("SpeakerPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnering.
        /// </summary>
        public static string Tournament {
            get {
                return ResourceManager.GetString("Tournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turneringen er allerede started.
        /// </summary>
        public static string TournamentAlreadyStarted {
            get {
                return ResourceManager.GetString("TournamentAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turneringer.
        /// </summary>
        public static string TournamentListPageTitle {
            get {
                return ResourceManager.GetString("TournamentListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan ikke start turnreringen - Ingen dommere registrert.
        /// </summary>
        public static string TournamentNoJudges {
            get {
                return ResourceManager.GetString("TournamentNoJudges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For få utøvere registrert for å starte turneringen.
        /// </summary>
        public static string TournamentTooFewContestants {
            get {
                return ResourceManager.GetString("TournamentTooFewContestants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turneringen er ikke aktiv.
        /// </summary>
        public static string TourneyNotRunning {
            get {
                return ResourceManager.GetString("TourneyNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oppdater.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string Whatever {
            get {
                return ResourceManager.GetString("Whatever", resourceCulture);
            }
        }
    }
}
