// <auto-generated />
namespace NordicArenaTournament.Database
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class ContestantsOnScoreboardToNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContestantsOnScoreboardToNull));
        
        string IMigrationMetadata.Id
        {
            get { return "201608110717410_ContestantsOnScoreboardToNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
